- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:

    # Stop Docker container
    - name: Stop Docker container
      docker_container:
        name: my_container
        image: containerguru1/mondayproj-1
        state: stopped
        ports:
          - "81:80"

    # Remove Docker container
    - name: Remove Docker container
      docker_container:
        name: my_container
        image: containerguru1/mondayproj-1
        state: absent

    # Remove old Docker image (Optional)
    - name: Remove Docker image
      docker_image:
        name: containerguru1/mondayproj-1
        state: absent

    # Ensure Docker is installed
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Docker Hub Login
    - name: Log in to Docker Hub
      docker_login:
        username: "containerguru1"
        password: "Madmithra!27"

    # Pull the latest Docker image from Docker Hub
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: containerguru1/mondayproj-1
        tag: latest
        source: pull

    # Start a new Docker container with the latest image
    - name: Start Docker container
      docker_container:
        name: my_container
        image: containerguru1/mondayproj-1
        state: started
        restart_policy: always
        ports:
          - "81:80"
