- remote_user: ubuntu
  hosts: all
  become: yes
  tasks:

    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure ubuntu user is in the docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Log in to Docker Hub
      docker_login:
        username: "containerguru1"
        password: "Madmithra!27"

    - name: Check if the image exists locally
      command: docker images containerguru1/mondayproj-1:latest
      register: image_check
      ignore_errors: true

    - name: Pull the image from Docker Hub if not exists
      docker_image:
        name: containerguru1/mondayproj-1
        tag: latest
        source: pull
      when: image_check.rc != 0

    - name: Stop Docker container
      docker_container:
        name: mondayproj1
        image: containerguru1/mondayproj-1
        state: stopped

    - name: Remove Docker container
      docker_container:
        name: mondayproj1
        image: containerguru1/mondayproj-1
        state: absent

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: mondayproj1
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: mondayproj1  # Container name
        image: mondayproj1  # Image name
        state: started
        restart_policy: always
        ports:
          - "81:80"

 

