- remote_user: ubuntu
  hosts: all
  become: yes
  tasks:

    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure ubuntu user is in the docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Stop Docker container
      docker_container:
        name: my_container
        state: stopped

    - name: Remove Docker container
      docker_container:
        name: my_container
        state: absent

    - name: Remove Docker image
      docker_image:
        name: containerguru1/mondayproj-1
        state: absent

    - name: Log in to Docker Hub
      docker_login:
        username: "containerguru1"
        password: "Madmithra!27"

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: containerguru1/mondayproj-1
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: my_container
        image: containerguru1/mondayproj-1
        state: started
        restart_policy: always
        ports:
          - "81:80"
