---
- name: Deploy Docker container on EC2
  hosts: all
  become: yes
  vars:
    docker_image: "containerguru1/mondayproj-1"  # Docker image name
    docker_tag: "latest"  # Tag of the Docker image

  tasks:

    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to Docker Hub
      docker_login:
        username: "containerguru1"  # Replace with your Docker Hub username
        password: "Madmithra!27"  # Replace with your Docker Hub password

    - name: Stop and remove existing container (if any)
      docker_container:
        name: mondayproj-1
        state: absent
      ignore_errors: true  # Ignore if the container doesn't exist

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: mondayproj-1
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        restart_policy: always
        exposed_ports:
          - "81"
        published_ports:
          - "81:81"  # Change if necessary
